# This is a reusable workflow that allows you to run semantic-release on your project.

# Define the event that triggers the workflow.
# This workflow is triggered by a workflow call event.
on:
  workflow_call:

# Define the jobs that run in the workflow.
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Step 2: Run the release process using the semantic-release action.
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
